name: dvsg-env

channels:
  - conda-forge

dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy=1.13.1
  - matplotlib=3.9.2
  - astropy=6.0.1
  - wheel=0.45.1
  - packaging=22.0
  - pip
  - pip:
    - pytest
    - sdss-marvin>=2.8.1
    - sdss-mangadap==4.1.1
    - smplotlib
    - git+https://github.com/jmpowley/dvsg.git
